# Generated by Django 5.1.6 on 2025-07-12 10:34

import django.db.models.deletion
import story_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebStory",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=story_app.models.get_short_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="The main image shown before the story starts. Recommended size: 600x1200px.",
                        null=True,
                        upload_to="cover_images/",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Web Story",
                "verbose_name_plural": "Web Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebStorySlide",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=story_app.models.get_short_id,
                        editable=False,
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Order of the slide in the story. Lower numbers appear first.",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image for the slide. Recommended size: 600x1200px.",
                        upload_to="slides/",
                    ),
                ),
                (
                    "caption",
                    models.TextField(
                        blank=True,
                        help_text="Caption text overlay for the slide.",
                        null=True,
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slides",
                        to="story_app.webstory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Web Story Slide",
                "verbose_name_plural": "Web Story Slides",
                "ordering": ["story", "order"],
            },
        ),
    ]
