# Generated by Django 5.2.4 on 2025-07-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_app', '0002_alter_webstory_id_alter_webstory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webstoryslide',
            name='image',
            field=models.ImageField(blank=True, help_text='Image for the slide. Recommended size: 600x1200px.', null=True, upload_to='slides/'),
        ),
    ]
